### ISSUE TITLE
Server Crash 1.12

### ISSUE THREAD

**Issue by ivardensphere** [gottsch/gottsch-minecraft-Metals#3]
Version: Metals-mc1.12-v3.0.1
Forge: forge-1.12-14.21.1.2443-universal
Minecraft: 1.12
Crashlog: https://gist.github.com/ivardensphere/f79692428320342054e40ebd7f068bfd

Please let me know if you need more information.

**Comment by gottsch** [comment]
This looks like an easy one. I should be able to get to it shortly.

**Comment by gottsch** [comment]
Actually, try using the recommended forge version 14.21.1.2387.
